name: Pipeline Basico DevOps

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  ejecutar-echo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Ejecutar el comando Echo
        run: echo "¡Hola profe! Pipeline ejecutado con exito sin compilar el codigo, solo usando echo."